language: es

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  epochs: 100
assistant_id: 20260309-205029-sizzling-osprey
